using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SK.SerendipGenericService.KTesellumApi.Core.Entities
{
    public class KTesellum
    {
        [Key]
        public long ObjId { get; set; }
        public byte[] Sistem_Timestamp { get; set; }
        public bool? Aktif { get; set; }
        public long? FaturalayacakSube_ObjId { get; set; }
        public long? Faturasi_ObjId { get; set; }
        public long? IadeTesellum_ObjId { get; set; }
        public int? OdemeSekli { get; set; }
        public long? Sirketi_ObjId { get; set; }
        public string Sistem_InsertLogin { get; set; }
        public DateTime? Sistem_InsertTime { get; set; }
        public string Sistem_TransactionId { get; set; }
        public string Sistem_UpdateLogin { get; set; }
        public DateTime? Sistem_UpdateTime { get; set; }
        public long? TahsilatSubesi_ObjId { get; set; }
        public long? TATNo { get; set; }
        public string TEFAliciAciklama { get; set; }
        public long? TEFAliciAdresi_ObjId { get; set; }
        public long? TEFAliciBolge_ObjId { get; set; }
        public long? TEFAliciCarisi_ObjId { get; set; }
        public string TEFAliciKodu { get; set; }
        public long? TEFAliciSube_ObjId { get; set; }
        public string TEFAliciUnvan { get; set; }
        public long? TEFAraciFirmaHareketi_AraciFirma_ObjId { get; set; }
        public long? TEFAraciFirmaHareketi_AraciFirmaSube_ObjId { get; set; }
        public long? TEFAraciFirmaHareketi_Faturasi_ObjId { get; set; }
        public decimal? TEFAraciFirmaHareketi_KDVOrani { get; set; }
        public decimal? TEFAraciFirmaHareketi_KDVTutar_IslemDoviziTutari { get; set; }
        public long? TEFAraciFirmaHareketi_KDVTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? TEFAraciFirmaHareketi_KDVTutar_RaporDoviziTutari { get; set; }
        public decimal? TEFAraciFirmaHareketi_KDVTutar_YerelTutar { get; set; }
        public string TEFAraciFirmaHareketi_TakipNo { get; set; }
        public DateTime? TEFAraciFirmaHareketi_Tarih { get; set; }
        public decimal? TEFAraciFirmaHareketi_ToplamTutar_IslemDoviziTutari { get; set; }
        public long? TEFAraciFirmaHareketi_ToplamTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? TEFAraciFirmaHareketi_ToplamTutar_RaporDoviziTutari { get; set; }
        public decimal? TEFAraciFirmaHareketi_ToplamTutar_YerelTutar { get; set; }
        public long? TEFBorcluAdresi_ObjId { get; set; }
        public long? TEFBorcluCarisi_ObjId { get; set; }
        public string TEFBorcluKodu { get; set; }
        public string TEFBorcluUnvan { get; set; }
        public long? TEFDonemi_ObjId { get; set; }
        public long? TEFEvrakAyari_ObjId { get; set; }
        public int? TEFFiyatTipi { get; set; }
        public string TEFGonderenAciklama { get; set; }
        public long? TEFGonderenAdresi_ObjId { get; set; }
        public long? TEFGonderenBolge_ObjId { get; set; }
        public long? TEFGonderenCarisi_ObjId { get; set; }
        public string TEFGonderenKodu { get; set; }
        public long? TEFGonderenSube_ObjId { get; set; }
        public string TEFGonderenUnvan { get; set; }
        public long? TEFHizmeti_ObjId { get; set; }
        public bool? TEFIptal { get; set; }
        public long? TEFIptalBilgisi_ObjId { get; set; }
        public int? TEFIptalDurumu { get; set; }
        public long? TEFIslemDovizTuru_ObjId { get; set; }
        public string TEFKargoTakipNo { get; set; }
        public long? TEFKargoTeslimat_ObjId { get; set; }
        public decimal? TEFKDVOrani { get; set; }
        public decimal? TEFKDVTutar_IslemDoviziTutari { get; set; }
        public long? TEFKDVTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? TEFKDVTutar_RaporDoviziTutari { get; set; }
        public decimal? TEFKDVTutar_YerelTutar { get; set; }
        public string TEFKonsimentoNumarasi { get; set; }
        public int? TEFMaliDurumu { get; set; }
        public string TEFMusteriEvrakSeriNo { get; set; }
        public decimal? TEFMusteriEvrakSiraNo { get; set; }
        public int? TEFOdemeSekliSozlesmeIliskisi { get; set; }
        public DateTime? TEFPlanlananTeslimTarihi { get; set; }
        public long? TEFProje_ObjId { get; set; }
        public string TEFSeriNo { get; set; }
        public decimal? TEFSiraNo { get; set; }
        public long? TEFSozlesmesi_ObjId { get; set; }
        public long? TEFTahsilatBolgesi_ObjId { get; set; }
        public DateTime? TEFTarih { get; set; }
        public int? TEFTeslimDurumu { get; set; }
        public int? TEFTeslimSekli { get; set; }
        public decimal? TEFToplamAdet { get; set; }
        public decimal? TEFToplamDesi { get; set; }
        public decimal? TEFToplamKG { get; set; }
        public decimal? TEFToplamTutar_IslemDoviziTutari { get; set; }
        public long? TEFToplamTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? TEFToplamTutar_RaporDoviziTutari { get; set; }
        public decimal? TEFToplamTutar_YerelTutar { get; set; }
        public long? TEFVarisSubesi_ObjId { get; set; }
        public bool? TEFYazdirildiMi { get; set; }
        public int? TesellumTuru { get; set; }
        public bool? IsMobilDagitim { get; set; }
        public long? TEFKibrisYurtIciSozlesmesi_ObjId { get; set; }
        public decimal? TEFKibrisYurtIciToplamTutar_IslemDoviziTutari { get; set; }
        public long? TEFKibrisYurtIciToplamTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? TEFKibrisYurtIciToplamTutar_RaporDoviziTutari { get; set; }
        public decimal? TEFKibrisYurtIciToplamTutar_YerelTutar { get; set; }
        public bool? IsUcak { get; set; }
        public int? KargoTasinmaSekli { get; set; }
        public int? Kutu_1Adet { get; set; }
        public int? Kutu_2Adet { get; set; }
        public int? Kutu_3Adet { get; set; }
        public int? Zarf_8Adet { get; set; }
        public bool? IsFaturalanacak { get; set; }
        public bool? Iskutu { get; set; }
        public string WebSiparisKodu { get; set; }
        public long? Pazarlamaci_ObjId { get; set; }
        public bool? IsUcakKesilecek { get; set; }
        public string TEFAciklama { get; set; }
        public int IsMobilaracUretimi { get; set; }
        public int? Kutu_4Adet { get; set; }
        public int? Kutu_5Adet { get; set; }
        public int? Zarf_6Adet { get; set; }
        public int? Zarf_7Adet { get; set; }
        public byte? IsOther { get; set; }
        public int? P261910Adet { get; set; }
        public int? Pudomu { get; set; }
        public int? P392924Adet { get; set; }
        public int? Z304005Adet { get; set; }
        public bool? IsKapidanTahsilatFaturasi { get; set; }
        public bool? IsMusteriTahsil { get; set; }
        public decimal? KapidanTahsilatTutari { get; set; }
        public long? KOCariHareketi_ObjId { get; set; }
        public decimal? TahsilatTutar_IslemDoviziTutari { get; set; }
        public long? TahsilatTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? TahsilatTutar_RaporDoviziTutari { get; set; }
        public decimal? TahsilatTutar_YerelTutar { get; set; }
        public bool? TahsilEdildimi { get; set; }
        public DateTime? KOPosCozumTarihi { get; set; }
        public bool IsGitGelEvrak { get; set; }
        public bool IsGitGelDonusEvrak { get; set; }
        public decimal? AraciSirketTutari { get; set; }
        public string Sistem_InsertTerminal { get; set; }
        public string Sistem_UpdateTerminal { get; set; }
        public decimal? SozlesmeArtisOrani { get; set; }
        public decimal? SozlesmeArtisOranTutari { get; set; }
        public bool? IsKoPOS { get; set; }
        public int? KargoGonderimSekli { get; set; }
        public int? TEFAraciFirmaAdi { get; set; }
        public bool? IsPosTaksit { get; set; }
        public long? KDesiKgKontrol_ObjId { get; set; }
        public decimal? TEFEphKDVTutar_IslemDoviziTutari { get; set; }
        public long? TEFEphKDVTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? TEFEphKDVTutar_RaporDoviziTutari { get; set; }
        public decimal? TEFEphKDVTutar_YerelTutar { get; set; }
        public decimal? TEFEphTutar_IslemDoviziTutari { get; set; }
        public long? TEFEphTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? TEFEphTutar_RaporDoviziTutari { get; set; }
        public decimal? TEFEphTutar_YerelTutar { get; set; }
        public long? KontrolEden_ObjId { get; set; }
        public string Icerik { get; set; }
        public long? Firma_ObjId { get; set; }
        public bool? IsEphHesaplansin { get; set; }
        public long? YFLSozlesmesi_ObjId { get; set; }
        public long? YFLEphTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? YFLEphTutar_IslemDoviziTutari { get; set; }
        public decimal? YFLEphTutar_RaporDoviziTutari { get; set; }
        public decimal? YFLEphTutar_YerelTutar { get; set; }
        public long? YFLEphKDVTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? YFLEphKDVTutar_IslemDoviziTutari { get; set; }
        public decimal? YFLEphKDVTutar_RaporDoviziTutari { get; set; }
        public decimal? YFLEphKDVTutar_YerelTutar { get; set; }
        public long? YFLKDVTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? YFLKDVTutar_IslemDoviziTutari { get; set; }
        public decimal? YFLKDVTutar_RaporDoviziTutari { get; set; }
        public decimal? YFLKDVTutar_YerelTutar { get; set; }
        public long? YFLToplamTutar_IslemDovizTuru_ObjId { get; set; }
        public decimal? YFLToplamTutar_IslemDoviziTutari { get; set; }
        public decimal? YFLToplamTutar_RaporDoviziTutari { get; set; }
        public decimal? YFLToplamTutar_YerelTutar { get; set; }
        public string MikroKcaKodu { get; set; }
    }
}